<?php
session_start();
include('config/dbconf.php');
include('includes/head.php');
include('includes/nav.php');
include('includes/left-side.php');
include('includes/body.php');
include('includes/right-side.php');
include('includes/foot.php');
?>
